[package]
name = "cygnus"
version = "0.1.0"
edition = "2023_11"
cairo-version = "2.6.4"
scarb-version = "2.6.5"
authors = ["Swan of Bodom <0xhyoga@cygnusdao.finance>"]
description = "CygnusDAO contracts written in Cairo for StarkNet, a decentralized ZK Rollup"
documentation = "https://docs.cygnusdao.finance"
readme = "README.md"
license-file = "LICENSE"
keywords = ["cygnusdao", "starknet", "cairo", "contracts", "defi"]

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.6.4"
erc6909 = { git = "https://github.com/swan-of-bodom/erc6909-starknet" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.14.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.26.0" }

[[target.starknet-contract]]
sierra = true
casm = false

[scripts]
test = "snforge test"

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[tool.snforge]
exit_first = true
